### ISSUE TITLE
prediction python script fails to write result csv

### ISSUE THREAD

**Issue by sbthandras** [phageaisa/phageai#6]
Using your example script, when all prediction is done, this error is produced when python tries to create the result csv.
The results are pasted into stdout instead (or nohup if you're using it)
I'm linking the full report log and the script itself here: 

https://www.file.io/4Bj9/download/MtcAmPXJauF6
  
  File "predict.py", line 40, in <module>
    writer.writerow(phage_data)
  File "/usr/lib/python3.8/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'hash'

**Comment by krzysieqq** [comment]
Hi,
Next time try to search error message in a web search. You can find the answer to your question faster :)

The problem isn't now with our package but with your code. You try to write a row with dict (`phage_data`) that contains more data than you declare in `csv_columns`. The fastest way to solve this is pass to the `csv.DictWriter` optional param `extrasaction='ignore'` parameter (https://docs.python.org/3.8/library/csv.html#csv.DictWriter`

**Comment by sbthandras** [comment]
I've copied the script from your website/github as far as I can recall
