### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by conchaeloko** [phageaisa/phageai#7]
Hi ! 
Thanks for the tool ! I have used it in the past and wanted to complete the life cycle prediction from a set of newly isolated phages. However, I get this message error : "Expecting value: line 1 column 1 (char 0)" for each of my fasta files. 
Do you have an idea of what could cause this error ?

Best,

**Comment by krzysieqq** [comment]
Hi!
Do you update your package and use the newest version? Can you paste the phageai package version which you have in your env?

Feel free to use:
```
pip list | grep phageai
```

**Comment by conchaeloko** [comment]
Hi,
It worked after the update : I was still using the version 0.1.0.
Thanks for the help !
