### ISSUE TITLE
Bug in code on Example II - prediction for directory with phages & solution

### ISSUE THREAD

**Issue by juanorl** [phageaisa/phageai#8]
Description:
I encountered an error while running the **Example II - prediction for directory with phages & solution** script. The error occurs when writing data to a CSV file and states that the dictionary contains fields not present in the specified csv_columns. I have identified the issue and found that the following fields are missing in the csv_columns list: 'hash' and 'predicted_lifecycle'.

**Traceback (most recent call last):
  File "phage_ai.py", line 42, in <module>
    writer.writerow(phage_data)
  File "/home/anaconda3/envs/phageai/lib/python3.8/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/home/juanfelix/anaconda3/envs/phageai/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'hash', 'predicted_lifecycle'**

The csv_columns list should include all the required fields, including 'hash' and 'predicted_lifecycle', to avoid the ValueError during the CSV writing process.

Before in line 28:

```
csv_columns = [
    'fasta_name', 'model_class_label', 'prediction_accuracy',
    'gc', 'sequence_length'
]
```

Solution in line 28
To resolve the issue, I suggest updating the csv_columns list to include the missing fields as follows:

```
csv_columns = [
    'fasta_name', 'model_class_label', 'prediction_accuracy',
    'gc', 'sequence_length', 'hash', 'predicted_lifecycle'
]
```

This modification will ensure that all the required fields are present when writing data to the CSV file, preventing the ValueError from occurring.

**Comment by phageaisa** [comment]
Fixed with phageai v0.4.2.
