### ISSUE TITLE
ModuleNotFoundError: No module named 'phageai.lifecycle'; 'phageai' is not a package

### ISSUE THREAD

**Issue by TarsLi** [phageaisa/phageai#9]
Dear phageai team,
Thank you for developing useful tools! I installed the latest version (0.4.1) according to the tutorial and successfully tested a sequence. But when I used the tool for the second time, the following error always popped up. 
**ModuleNotFoundError: No module named 'phageai.lifecycle'; 'phageai' is not a package**
How can I solve this? 
In addition, I need to predict the lifestyle of 4,000 vOTUs. Can the API be used to complete it? 
Thank you!

**Comment by krzysieqq** [comment]
Hi!
For the first time, did you use virtualenv? Maybe the second time you forgot to activate it?

**Comment by phageaisa** [comment]
@TarsLi Any new updates with the issue?
